### ISSUE TITLE
MethSig-array

### ISSUE THREAD

**Issue by ChengYunazhi** [HengPan2007/MethSig#1]
Hi, Where can I find MethSig-array ？

Thanks ！

**Comment by ChengYunazhi** [comment]
Hi, Where can I find MethSig-array ？

<img width="1544" alt="image" src="https://user-images.githubusercontent.com/13846735/122369128-834c7b80-cf90-11eb-88b6-7176a23f7aed.png">


Thanks ！

**Comment by HengPan2007** [comment]
Thank you for your interest. You can build your own input matrix and a beta regression formula. 
 

- In Step 2 of Prerequisite, replace DHcR_Normal with average promoter methylation in normal samples and get rid of PDR_Normal.
- In Input matrix generation, add average promoter methylation of each tumor sample to the input matrix.
- In Sample-specific hypermethylation inference, use your own input matrix and a customized formula, something like Meth_Tumor_Beta~Meth_Normal+GEXP_Normal+Reptime.
- The Cohort-prevalent hypermethylation inference will be same.

Hopefully this is clear enough. Thanks.

Best,
Heng
