### ISSUE TITLE
methsig-array was not found

### ISSUE THREAD

**Issue by hust-yyan** [HengPan2007/MethSig#2]
Hello, now I have the methylation array data of lung cancer tissue. After reading your article, I found that methsig-array can be used for analysis, but this pipeline is not found in the current project. Could you please provide the specific link? Thank you very much!

**Comment by HengPan2007** [comment]
Thank you for your interest. You can build your own input matrix and a beta regression formula. 
 
- In Step 2 of Prerequisite, replace DHcR_Normal with average promoter methylation in normal samples and get rid of PDR_Normal.
- In Input matrix generation, add average promoter methylation of each tumor sample to the input matrix.
- In Sample-specific hypermethylation inference, use your own input matrix and a customized formula, something like Meth_Tumor_Beta~Meth_Normal+GEXP_Normal+Reptime.
- The Cohort-prevalent hypermethylation inference will be same.

Hopefully this is clear enough. Thanks.

Best,
Heng
